

<h1 class="title is-block">Bienvenido Jefe de Mesa</h1>
<div class="columns">
    <div class="column pt-0">
        <aside id="menuJefeMesa" class="menu p-4 has-background-white">
            <p class="menu-label">
                Administración
            </p>
            <ul class="menu-list">
                <li>
                    <div class="dropdown is-hoverable is-block">
                        <div class="dropdown-trigger">
                            <a class="" aria-haspopup="true" aria-controls="dropdown-menu4">
                                <span>Usuarios</span>
                                <span class="icon is-small"><i class="fas fa-angle-down" aria-hidden="true"></i></span>
                            </a>
                        </div>
                        <div class="dropdown-menu has-addons-fullwidth" id="dropdown-menu4" role="menu">
                            <div class="dropdown-content">
                                <a id="usuarios" href="#" class="dropdown-item">
                                    Crear
                                </a>
                                <a href="#" class="dropdown-item">
                                    Deshabilitar
                                </a>
                            </div>
                        </div>
                    </div>
                </li>
                <li><a id="criticidad">Criticidad</a></li>
                <li><a id="tipoArea">Tipo Áreas</a></li>
            </ul>
        </aside>
    </div>
    <div id="rootContainer" class="column is-three-quarters has-text-white is-bordered has-background-white">
      <div class="p-4 is-flex is-justify-content-center container" id="root"></div>
    </div>
</div>
<script src="<?=BASE_URL?>/js/app.js"></script>

