<?php

/** @var $rolId */
/** @var $manageView */
?>

<?php require_once __DIR__ . '../../messages-modal.phtml' ?>
<h1 class="title is-block">Bienvenido Ejecutivo de Área</h1>
<div class="columns">
    <div class="column pt-0">
        <aside id="menuJefeMesa" class="menu p-4 has-background-white">
            <p class="menu-label">
                Administración
            </p>
            <ul class="menu-list">
                <li><a id="criticidad" href="<?=BASE_URL?>/admin-home/tiques/">Ver Tiques</a></li>
                <li><a href="<?=BASE_URL.'/admin-home/cerrar'?>">Cerrar Sesión</a></li>
            </ul>
        </aside>
    </div>
    <div id="rootContainer" class="column is-three-quarters has-text-white is-bordered has-background-white">
        <div class="p-4 is-flex is-justify-content-center container" id="root">

            <?php if( isset($manageView) ): ?>
                <?php require_once __DIR__.'/'.$manageView.'.phtml'; ?>
            <?php else: ?>
                <p class="has-text-black">Dashboard papu</p>
            <?php endif; ?>

        </div>
    </div>
</div>