<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistema Tiques</title>
    <link rel="stylesheet" href="<?=BASE_URL?>/css/bulma.css">
    <link rel="stylesheet" href="<?=BASE_URL?>/css/mystyles.css">
    <!-- Cargar React. -->
    <!-- Nota: cuando se despliegue, reemplazar "development.js" con "production.min.js". -->
    <!--
    <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
    <script src="<?=BASE_URL?>/js/components/Form/forms.js"></script>
    <script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>-->
    <script src="<?=BASE_URL?>/js/modal/modal.js?t=<?=time()?>"></script>
    <script src="https://kit.fontawesome.com/81bf225702.js" crossorigin="anonymous"></script>
    <script src="<?=BASE_URL?>/js/validations/validations.js?t=<?=time()?>"></script>
</head>
<body>

