

<section class="section">
    <div class="container">
        <form class="" method="POST" action="<?=BASE_URL?>/admins-login">

            <div class="field">
                <label class="label">Rut</label>
                <div class="control">
                    <input class="input" type="text" name="rut">
                </div>
            </div>

            <div class="field">
                <label class="label">Contraseña</label>
                <div class="control">
                    <input class="input" type="password" name="password">
                </div>
            </div>

            <div class="field">
                <input class="button" type="submit" value="Ingresar">
            </div>
        </form>
    </div>
</section>
