<?php

/** @var $data */
?>

<div id="jefe-mesa-usuario-2" class="is-100-width has-text-black is-full has-background-grey-lighter has-border p-2 is-bordered">
    <div class="table-container is-100-width">
        <table class="talbe is-100-width">
            <thead>
            <tr class="has-text-centered">
                <th>ID</th>
                <th>RUT</th>
                <th>Tipo Usuario</th>
                <th>Area</th>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Acciones</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($data as $user): ?>
                <tr class="has-text-centered">
                    <th class="pt-2 pb-2"><?=$user['id_usuario']?></th>
                    <td class="pt-2 pb-2"><?=$user['rut']?></td>
                    <td class="pt-2 pb-2"><?=$user['id_tipo']?></td>
                    <td class="pt-2 pb-2"><?=$user['id_area']?></td>
                    <td class="pt-2 pb-2"><?=$user['nombre']?> <?=$user['apellido']?></td>
                    <td class="pt-2 pb-2"><?=$user['correo']?></td>
                    <td class="pt-2 pb-2">
                        <button class="button is-success is-size-7">Acciones</button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
